config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: "posts#index"

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum: 3, maximum: 100}
	validates :content, presence: true, length: {minimum: 10}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	before_save {self.email = email.downcase }
	validates 	:username, presence: true, length: {minimum: 3, maximum: 50}, 
				uniqueness: { case_sensitive: false }
	EMAIL_VALID_REGEX = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/i
	validates :email, presence: true, uniqueness: {case_sensitive: false},
	format: {with: EMAIL_VALID_REGEX} 
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.last
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :post_type, :price, :phone)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			#flash[:success] = "You have signed up successfully #{{@user.username}}"
			redirect_to posts_path
		else
			render 'new'
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to posts_path
		else		
			render 'edit'
		end
	end
	def show
		@user = User.find(params[:id])
		@user_all = @user.posts.paginate(page: params[:page], per_page: 1)
	end
	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cambbus", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Latest Posts</a></li>
         <li><%= link_to "New Article", new_post_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", signup_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cambbus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation alert alert-danger">
        <b><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</b>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container container-min">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :post_type %><br>
        <%= f.text_field :post_type, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %><br>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        
      </div>
      <div class="form-group">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-lg btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <%= render 'messages' %>
  <h1>Listing Posts</h1>
    <div class="row">
      <% @posts.each do |post| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <%= link_to(post) do %>
              <%= image_tag("image_upload.png", :alt => "images thumbnail", :class => "img-responsive") %>
              <% end %>
              <div class="caption">
                <h3><td><%= link_to post.title, post %></td></h3>
                <p>
                  <small>Posted by: <%= link_to post.user.username, user_path(post.user) %> - <em><%= time_ago_in_words(post.created_at) %> ago</em></small>
                </p>
                <p><%= truncate(post.content, length: 100) %></p>
                <p>
                  <%= link_to 'Edit', edit_post_path(post), class: "btn btn-sm btn-success" %>
                  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
                </p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
    <%= will_paginate %>
  <br>
  
  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'messages' %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<div class="container container-min">
	<%= form_for(@user) do |f| %>
		
		<% if @user.errors.any? %>
			<div class="alert alert-danger alert-error">
				<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><i class="fa fa-exclamation-triangle"></i> <%= msg %></li>
				<% end %>
				</ul>
			</div>
		<%end%>
		
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, placeholder: "Enter username", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.email_field :email, placeholder: "Enter email", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, placeholder: "Enter password", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.submit(@user.new_record? ? "Sign Up" : "Edit User" , class: "btn btn-lg btn-info") %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Show listing</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to user.username, user_path(user) %> </li> 
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
	<h1 class="center">Show user</h1>

	<%= @user.username %>

	<div class="row user-post">
	  <% @user_all.each do |post| %>
	      <div class="col-sm-4 col-md-3">
	        <div class="thumbnail">
	          <%= link_to(post) do %>
	          <%= image_tag("image_upload.png", :alt => "images thumbnail", :class => "img-responsive") %>
	          <% end %>
	          <div class="caption">
	            <h3><td><%= link_to post.title, post %></td></h3>
	            <p>
	              <small>Posted by: <%= post.user.username %> - <em><%= time_ago_in_words(post.created_at) %> ago</em></small>
	            </p>
	            <p><%= truncate(post.content, length: 100) %></p>
	            <p>
	              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-sm btn-success" %>
	              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
	            </p>
	          </div>
	        </div>
	      </div>
	  <% end %>
	</div>
	<%= will_paginate @user_all %>
</div>